export const DEFAULT_POSTS: string[] = [
  "Présidente",
  "Vice presidente",
  "Past presidente",
  "Tresorier",
  "Tresorier adjoint",
  "Protocole",
  "Protocole adjointe",
  "Representante cnit",
  "Secrétaire",
  "Secrétaire adjoint",
  "Cheffe RRH",
  "Cheffe interet public",
  "Co chef interet public",
  "Cheffe internationale",
  "Cheffe finance",
  "Chef ie",
  "Cheffe media",
  "Membre",
];
